### ISSUE TITLE
Error: device was not found in smartdb JSON file.

### ISSUE THREAD

**Issue by ijunaid8088** [smeinecke/check_smart_attributes#1]
I am following this link https://www.thomas-krenn.com/de/wiki/SMART_Attributes_Monitoring_Plugin#MegaRAID_Controller

But it just give me this in return:
```
/usr/lib/nagios/plugins/check_smart_attributes -d megaraid6, /dev/sda6 -dbj /etc/nagios-plugins/config/check_smartdb.json
```
returning as

```
`Error: device was not found in smartdb JSON file.`
```

**Comment by smeinecke** [comment]
Hi, sorry, this is an outdated repository as thomas-krenn did not have any back in 2015 on github.
Please check out their repo on https://github.com/thomas-krenn/check_smart_attributes
